[phases.setup]
nixPkgs = ['temurin-bin-21']

[phases.install]
cmds = ['./gradlew --version']

[phases.build]
cmds = ['./gradlew clean bootJar -x test --no-daemon']

[phases.start]
cmd = 'java -Dserver.port=$PORT -jar build/libs/app.jar'

[variables]
GRADLE_OPTS = '-Dorg.gradle.daemon=false'
